#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "Usage: $0 [--build-dir DIR] [--dist-dir DIR] [--arch ARCH]"
    echo "          [--channel portable|steamrt4] [--formats LIST]"
    echo
    echo "Formats are a comma-separated subset of: appimage,tar,deb,rpm."
}

repo_root="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="${repo_root}/build/linux-release"
dist_dir="${repo_root}/build/linux-dist"
architecture="$(uname -m)"
channel="portable"
formats=""

while (($# > 0)); do
    case "$1" in
        --build-dir)
            build_dir="$2"
            shift 2
            ;;
        --dist-dir)
            dist_dir="$2"
            shift 2
            ;;
        --arch)
            architecture="$2"
            shift 2
            ;;
        --channel)
            channel="$2"
            shift 2
            ;;
        --formats)
            formats="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

build_dir="$(realpath "$build_dir")"
mkdir -p "$dist_dir"
dist_dir="$(realpath "$dist_dir")"

if [[ "$channel" != "portable" && "$channel" != "steamrt4" ]]; then
    echo "Unsupported channel: $channel" >&2
    exit 2
fi

if [[ -z "$formats" ]]; then
    if [[ "$channel" == "portable" ]]; then
        formats="appimage,tar,deb,rpm"
    else
        formats="tar"
    fi
fi

IFS=',' read -r -a requested_formats <<< "$formats"
for requested_format in "${requested_formats[@]}"; do
    case "$requested_format" in
        appimage|tar|deb|rpm)
            ;;
        *)
            echo "Unsupported package format: ${requested_format}" >&2
            exit 2
            ;;
    esac
done

has_format() {
    [[ ",${formats}," == *",$1,"* ]]
}

case "$architecture" in
    x86_64|amd64)
        canonical_arch="x86_64"
        appimage_arch="x86_64"
        deb_arch="amd64"
        rpm_arch="x86_64"
        file_arch_pattern="x86-64"
        ;;
    aarch64|arm64)
        canonical_arch="aarch64"
        appimage_arch="aarch64"
        deb_arch="arm64"
        rpm_arch="aarch64"
        file_arch_pattern="ARM aarch64"
        ;;
    *)
        echo "Unsupported Linux architecture: $architecture" >&2
        exit 2
        ;;
esac

package_info="${build_dir}/package-info.env"
if [[ ! -f "$package_info" ]]; then
    echo "Missing ${package_info}; configure the Linux build before packaging." >&2
    exit 1
fi

# Generated by CMake from fixed project metadata.
source "$package_info"
version="${MOONLIGHT_PACKAGE_VERSION}"
executable="${MOONLIGHT_PACKAGE_EXECUTABLE}"

work_dir="$(mktemp -d "${TMPDIR:-/tmp}/moonlight-linux-package.XXXXXXXX")"
cleanup() {
    rm -rf -- "$work_dir"
}
trap cleanup EXIT

app_dir="${work_dir}/Moonlight-Switch.AppDir"
mkdir -p "$app_dir"
DESTDIR="$app_dir" cmake --install "$build_dir" --component Runtime

binary="${app_dir}/usr/bin/${executable}"
if [[ ! -x "$binary" ]]; then
    echo "Installed executable is missing: $binary" >&2
    exit 1
fi

if ! file "$binary" | grep -q "$file_arch_pattern"; then
    echo "Executable architecture does not match ${canonical_arch}:" >&2
    file "$binary" >&2
    exit 1
fi

unbundled_ldd="$(ldd "$binary")"
if grep -q "not found" <<< "$unbundled_ldd"; then
    echo "The unbundled executable has unresolved dependencies:" >&2
    echo "$unbundled_ldd" >&2
    exit 1
fi
requires_opencl=false
if grep -q 'libOpenCL\.so' <<< "$unbundled_ldd"; then
    requires_opencl=true
fi

ln -s "$executable" "${app_dir}/usr/bin/moonlight-switch"

linuxdeploy="${LINUXDEPLOY:-${work_dir}/linuxdeploy-${appimage_arch}.AppImage}"
if [[ ! -x "$linuxdeploy" ]]; then
    linuxdeploy_url="https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${appimage_arch}.AppImage"
    if command -v curl >/dev/null; then
        curl --fail --location --retry 3 \
            "$linuxdeploy_url" --output "$linuxdeploy"
    elif command -v wget >/dev/null; then
        wget --tries=3 --output-document="$linuxdeploy" "$linuxdeploy_url"
    else
        echo "Packaging requires curl or wget to download linuxdeploy." >&2
        exit 1
    fi
    chmod +x "$linuxdeploy"
fi

linuxdeploy_args=(
    --appdir "$app_dir"
    --desktop-file "${repo_root}/app/platforms/linux/ru.xitrix.Moonlight.desktop"
    --icon-file "${repo_root}/resources/img/moonlight_96.png"
    --icon-filename "ru.xitrix.Moonlight"
    --custom-apprun "${repo_root}/app/platforms/linux/AppRun"
    --exclude-library "libGL.so*"
    --exclude-library "libEGL.so*"
    --exclude-library "libGLES*.so*"
    --exclude-library "libGLX*.so*"
    --exclude-library "libOpenGL.so*"
    --exclude-library "libgbm.so*"
    --exclude-library "libdrm*.so*"
    --exclude-library "libva*.so*"
    --exclude-library "libvdpau.so*"
)

commit="${GITHUB_SHA:-unknown}"
{
    echo "Moonlight-Switch ${version}"
    echo "Architecture: ${canonical_arch}"
    echo "Channel: ${channel}"
    echo "Commit: ${commit}"
    echo "Hardware decoding: FFmpeg VA-API H.264 and HEVC required at configure time"
    if [[ "$channel" == "steamrt4" ]]; then
        echo "Steamworks Linux Runtime: Steam Linux Runtime 4.0"
        echo "Steam launch executable: AppRun"
    fi
} > "${app_dir}/BUILD-INFO.txt"

if has_format appimage; then
    linuxdeploy_args+=(--output appimage)
fi

(
    cd "$work_dir"
    APPIMAGE_EXTRACT_AND_RUN=1 \
    VERSION="$version" \
        "$linuxdeploy" "${linuxdeploy_args[@]}"
)

# These launchers are added after linuxdeploy creates an AppImage so its
# appimagetool sees only the application's primary desktop file. They are
# included in tar, DEB, and RPM packages for touch-friendly SteamOS setup.
install -m0755 "${repo_root}/app/platforms/linux/AppRun" \
    "${app_dir}/Moonlight-Switch"
install -m0755 "${repo_root}/app/platforms/linux/AddToSteam.sh" \
    "${app_dir}/AddToSteam.sh"
install -m0755 "${repo_root}/app/platforms/linux/Add-to-Steam.desktop" \
    "${app_dir}/Add-to-Steam.desktop"

for forbidden_library in \
    'libGL.so*' 'libEGL.so*' 'libGLES*.so*' 'libGLX*.so*' \
    'libOpenGL.so*' 'libgbm.so*' 'libdrm*.so*' 'libva*.so*' \
    'libvdpau.so*'; do
    if find "${app_dir}/usr/lib" -name "$forbidden_library" -print -quit |
            grep -q .; then
        echo "Host graphics library was bundled unexpectedly: ${forbidden_library}" >&2
        exit 1
    fi
done

if [[ "$requires_opencl" == true ]] &&
        ! find "${app_dir}/usr/lib" -name 'libOpenCL.so*' -print -quit |
            grep -q .; then
    echo "FFmpeg requires libOpenCL, but the OpenCL ICD loader was not bundled." >&2
    exit 1
fi

bundle_library_path="${app_dir}/usr/lib"
if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
    bundle_library_path+="${bundle_library_path:+:}${LD_LIBRARY_PATH}"
fi
if LD_LIBRARY_PATH="$bundle_library_path" ldd "$binary" | grep -q "not found"; then
    echo "The portable bundle has unresolved dependencies:" >&2
    LD_LIBRARY_PATH="$bundle_library_path" ldd "$binary" >&2
    exit 1
fi

artifact_base="Moonlight-Switch-${version}"
if [[ "$channel" == "steamrt4" ]]; then
    artifact_base+="-steamrt4"
else
    artifact_base+="-linux"
fi
artifact_base+="-${canonical_arch}"

if has_format appimage; then
    mapfile -t generated_appimages < <(
        find "$work_dir" -maxdepth 1 -type f -name '*.AppImage' \
            ! -name 'linuxdeploy-*.AppImage' -print
    )
    if ((${#generated_appimages[@]} != 1)); then
        echo "Expected one generated AppImage, found ${#generated_appimages[@]}" >&2
        exit 1
    fi
    install -Dm0755 "${generated_appimages[0]}" \
        "${dist_dir}/${artifact_base}.AppImage"
fi

if has_format tar; then
    tar --sort=name --owner=0 --group=0 --numeric-owner \
        -C "$work_dir" -czf "${dist_dir}/${artifact_base}.tar.gz" \
        "Moonlight-Switch.AppDir"
fi

if has_format deb; then
    command -v dpkg-deb >/dev/null
    deb_root="${work_dir}/deb-root"
    mkdir -p \
        "${deb_root}/DEBIAN" \
        "${deb_root}/opt/moonlight-switch" \
        "${deb_root}/usr/bin" \
        "${deb_root}/usr/share/applications" \
        "${deb_root}/usr/share/icons/hicolor/96x96/apps" \
        "${deb_root}/usr/share/metainfo"
    cp -a "${app_dir}/." "${deb_root}/opt/moonlight-switch/"
    ln -s /opt/moonlight-switch/AppRun \
        "${deb_root}/usr/bin/moonlight-switch"
    install -m0644 \
        "${repo_root}/app/platforms/linux/ru.xitrix.Moonlight.desktop" \
        "${deb_root}/usr/share/applications/ru.xitrix.Moonlight.desktop"
    install -m0644 "${repo_root}/resources/img/moonlight_96.png" \
        "${deb_root}/usr/share/icons/hicolor/96x96/apps/ru.xitrix.Moonlight.png"
    install -m0644 \
        "${app_dir}/usr/share/metainfo/ru.xitrix.Moonlight.metainfo.xml" \
        "${deb_root}/usr/share/metainfo/ru.xitrix.Moonlight.metainfo.xml"

    installed_size="$(du -sk "${deb_root}/opt/moonlight-switch" |
        awk '{print $1}')"
    sed \
        -e "s/@VERSION@/${version}/g" \
        -e "s/@DEB_ARCH@/${deb_arch}/g" \
        -e "s/@INSTALLED_SIZE@/${installed_size}/g" \
        "${repo_root}/app/platforms/linux/debian-control.in" \
        > "${deb_root}/DEBIAN/control"
    dpkg-deb --build --root-owner-group "$deb_root" \
        "${dist_dir}/moonlight-switch_${version}_${deb_arch}.deb"
fi

if has_format rpm; then
    command -v rpmbuild >/dev/null
    rpm_root="${work_dir}/rpmbuild"
    mkdir -p \
        "${rpm_root}/BUILD" "${rpm_root}/BUILDROOT" "${rpm_root}/RPMS" \
        "${rpm_root}/SOURCES" "${rpm_root}/SPECS" "${rpm_root}/SRPMS"
    tar --sort=name --owner=0 --group=0 --numeric-owner \
        -C "$app_dir" -czf \
        "${rpm_root}/SOURCES/moonlight-switch-bundle.tar.gz" .
    sed \
        -e "s/@RPM_VERSION@/${version}/g" \
        -e "s/@RPM_ARCH@/${rpm_arch}/g" \
        "${repo_root}/app/platforms/linux/moonlight-switch.spec.in" \
        > "${rpm_root}/SPECS/moonlight-switch.spec"
    rpmbuild --define "_topdir ${rpm_root}" \
        -bb "${rpm_root}/SPECS/moonlight-switch.spec"
    mapfile -t generated_rpms < <(
        find "${rpm_root}/RPMS" -type f -name '*.rpm' -print
    )
    if ((${#generated_rpms[@]} != 1)); then
        echo "Expected one generated RPM, found ${#generated_rpms[@]}" >&2
        exit 1
    fi
    install -Dm0644 "${generated_rpms[0]}" \
        "${dist_dir}/moonlight-switch-${version}-1.${rpm_arch}.rpm"
fi

find "$dist_dir" -maxdepth 1 -type f -printf '%f\n' | sort
