name: All Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

jobs:
  switch:
    name: Nintendo Switch
    uses: ./.github/workflows/docker-image.yml

  psvita:
    name: PS Vita
    uses: ./.github/workflows/psvita.yml

  android:
    name: Android
    uses: ./.github/workflows/android-apk.yml
    secrets: inherit

  macos:
    name: macOS
    uses: ./.github/workflows/macos.yml

  windows:
    name: Windows
    uses: ./.github/workflows/windows.yml

  linux:
    name: Linux
    uses: ./.github/workflows/linux.yml
